/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceCategory = IDL.Variant({
  'cleaning' : IDL.Null,
  'plumbing' : IDL.Null,
  'painting' : IDL.Null,
  'electrician' : IDL.Null,
  'acRepair' : IDL.Null,
  'carpentry' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'customer' : IDL.Principal,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'assignedProfessional' : IDL.Opt(IDL.Principal),
  'address' : IDL.Text,
  'serviceId' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const ProfessionalProfile = IDL.Record({
  'displayName' : IDL.Text,
  'category' : ServiceCategory,
});
export const UserProfile = IDL.Record({
  'role' : UserRole,
  'professional' : IDL.Opt(ProfessionalProfile),
});
export const PlatformStats = IDL.Record({
  'totalProfessionals' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalCompletedBookings' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'maxPrice' : IDL.Nat,
  'category' : ServiceCategory,
  'minPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceCategory, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignBookingToProfessional' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAssignedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getServicesByCategory' : IDL.Func(
      [IDL.Opt(ServiceCategory)],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'registerCustomer' : IDL.Func([], [], []),
  'registerProfessional' : IDL.Func([IDL.Text, ServiceCategory], [], []),
  'removeService' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, ServiceCategory, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceCategory = IDL.Variant({
    'cleaning' : IDL.Null,
    'plumbing' : IDL.Null,
    'painting' : IDL.Null,
    'electrician' : IDL.Null,
    'acRepair' : IDL.Null,
    'carpentry' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'customer' : IDL.Principal,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'assignedProfessional' : IDL.Opt(IDL.Principal),
    'address' : IDL.Text,
    'serviceId' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const ProfessionalProfile = IDL.Record({
    'displayName' : IDL.Text,
    'category' : ServiceCategory,
  });
  const UserProfile = IDL.Record({
    'role' : UserRole,
    'professional' : IDL.Opt(ProfessionalProfile),
  });
  const PlatformStats = IDL.Record({
    'totalProfessionals' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalCompletedBookings' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'maxPrice' : IDL.Nat,
    'category' : ServiceCategory,
    'minPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceCategory, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignBookingToProfessional' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAssignedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getServicesByCategory' : IDL.Func(
        [IDL.Opt(ServiceCategory)],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'registerCustomer' : IDL.Func([], [], []),
    'registerProfessional' : IDL.Func([IDL.Text, ServiceCategory], [], []),
    'removeService' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, ServiceCategory, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };