/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'customer' : Principal,
  'date' : string,
  'createdAt' : bigint,
  'assignedProfessional' : [] | [Principal],
  'address' : string,
  'serviceId' : bigint,
  'timeSlot' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface PlatformStats {
  'totalProfessionals' : bigint,
  'totalBookings' : bigint,
  'totalUsers' : bigint,
  'totalCompletedBookings' : bigint,
}
export interface ProfessionalProfile {
  'displayName' : string,
  'category' : ServiceCategory,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'maxPrice' : bigint,
  'category' : ServiceCategory,
  'minPrice' : bigint,
}
export type ServiceCategory = { 'cleaning' : null } |
  { 'plumbing' : null } |
  { 'painting' : null } |
  { 'electrician' : null } |
  { 'acRepair' : null } |
  { 'carpentry' : null };
export interface UserProfile {
  'role' : UserRole,
  'professional' : [] | [ProfessionalProfile],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<
    [string, string, ServiceCategory, bigint, bigint],
    bigint
  >,
  'assignBookingToProfessional' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[bigint, string, string, string], bigint>,
  'getAssignedBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getServicesByCategory' : ActorMethod<
    [[] | [ServiceCategory]],
    Array<Service>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'registerCustomer' : ActorMethod<[], undefined>,
  'registerProfessional' : ActorMethod<[string, ServiceCategory], undefined>,
  'removeService' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateService' : ActorMethod<
    [bigint, string, string, ServiceCategory, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];