/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'customer' : Principal,
  'date' : string,
  'createdAt' : bigint,
  'assignedProfessional' : [] | [Principal],
  'address' : string,
  'serviceId' : bigint,
  'timeSlot' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface BrandingConfig {
  'tagline' : string,
  'primaryColor' : string,
  'logoDataUrl' : [] | [string],
  'siteName' : string,
  'footerText' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'bookingId' : bigint,
  'text' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'senderRole' : string,
}
export interface CustomerInfo {
  'principal' : Principal,
  'mobileNumber' : [] | [string],
  'bookingCount' : bigint,
}
export interface PlatformStats {
  'totalProfessionals' : bigint,
  'totalBookings' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'totalCompletedBookings' : bigint,
}
export interface ProfessionalInfo {
  'latitude' : [] | [number],
  'principal' : Principal,
  'displayName' : string,
  'longitude' : [] | [number],
  'category' : ServiceCategory,
}
export interface ProfessionalProfile {
  'latitude' : [] | [number],
  'displayName' : string,
  'longitude' : [] | [number],
  'category' : ServiceCategory,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'maxPrice' : bigint,
  'category' : ServiceCategory,
  'minPrice' : bigint,
}
export type ServiceCategory = { 'dataRecovery' : null } |
  { 'desktopRepair' : null } |
  { 'networkSetup' : null } |
  { 'laptopRepair' : null } |
  { 'accessoriesSales' : null } |
  { 'computerSales' : null };
export interface UserProfile {
  'role' : UserRole,
  'mobileNumber' : [] | [string],
  'professional' : [] | [ProfessionalProfile],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<
    [string, string, ServiceCategory, bigint, bigint],
    bigint
  >,
  'adminRemoveUser' : ActorMethod<[Principal], undefined>,
  'adminUpdateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'assignBookingToProfessional' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[bigint, string, string, string], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerInfo>>,
  'getAssignedBookings' : ActorMethod<[], Array<Booking>>,
  'getBrandingConfig' : ActorMethod<[], BrandingConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getNearbyTechnicians' : ActorMethod<[], Array<ProfessionalInfo>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getServicesByCategory' : ActorMethod<
    [[] | [ServiceCategory]],
    Array<Service>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProfessionals' : ActorMethod<[], Array<ProfessionalInfo>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'registerCustomer' : ActorMethod<[], undefined>,
  'registerProfessional' : ActorMethod<[string, ServiceCategory], undefined>,
  'removeService' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], bigint>,
  'setBrandingConfig' : ActorMethod<[BrandingConfig], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateMobileNumber' : ActorMethod<[string], undefined>,
  'updateService' : ActorMethod<
    [bigint, string, string, ServiceCategory, bigint, bigint],
    undefined
  >,
  'updateTechnicianLocation' : ActorMethod<[number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];