/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Service {
    id: bigint;
    name: string;
    description: string;
    maxPrice: bigint;
    category: ServiceCategory;
    minPrice: bigint;
}
export interface ProfessionalProfile {
    displayName: string;
    category: ServiceCategory;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    customer: Principal;
    date: string;
    createdAt: bigint;
    assignedProfessional?: Principal;
    address: string;
    serviceId: bigint;
    timeSlot: string;
}
export interface PlatformStats {
    totalProfessionals: bigint;
    totalBookings: bigint;
    totalUsers: bigint;
    totalRevenue: bigint;
    totalCompletedBookings: bigint;
}
export interface UserProfile {
    role: UserRole;
    professional?: ProfessionalProfile;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed",
    inProgress = "inProgress"
}
export enum ServiceCategory {
    dataRecovery = "dataRecovery",
    desktopRepair = "desktopRepair",
    networkSetup = "networkSetup",
    laptopRepair = "laptopRepair",
    accessoriesSales = "accessoriesSales",
    computerSales = "computerSales"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addService(name: string, description: string, category: ServiceCategory, minPrice: bigint, maxPrice: bigint): Promise<bigint>;
    assignBookingToProfessional(bookingId: bigint, professional: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<void>;
    createBooking(serviceId: bigint, date: string, timeSlot: string, address: string): Promise<bigint>;
    getAssignedBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBookings(): Promise<Array<Booking>>;
    getPlatformStats(): Promise<PlatformStats>;
    getServicesByCategory(category: ServiceCategory | null): Promise<Array<Service>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isAdminCaller(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listServices(): Promise<Array<Service>>;
    registerCustomer(): Promise<void>;
    registerProfessional(displayName: string, category: ServiceCategory): Promise<void>;
    removeService(serviceId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBookingStatus(bookingId: bigint, status: BookingStatus): Promise<void>;
    updateService(serviceId: bigint, name: string, description: string, category: ServiceCategory, minPrice: bigint, maxPrice: bigint): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, ProfessionalProfile as _ProfessionalProfile, Service as _Service, ServiceCategory as _ServiceCategory, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addService(arg0: string, arg1: string, arg2: ServiceCategory, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async assignBookingToProfessional(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBookingToProfessional(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBookingToProfessional(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAssignedBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedBookings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedBookings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getServicesByCategory(arg0: ServiceCategory | null): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByCategory(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByCategory(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCustomer(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer();
            return result;
        }
    }
    async registerProfessional(arg0: string, arg1: ServiceCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfessional(arg0, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfessional(arg0, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async removeService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeService(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: string, arg2: string, arg3: ServiceCategory, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, arg2, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, arg2, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_BookingStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ProfessionalProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfessionalProfile): ProfessionalProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfessionalProfile]): ProfessionalProfile | null {
    return value.length === 0 ? null : from_candid_ProfessionalProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _UserRole;
    professional: [] | [_ProfessionalProfile];
}): {
    role: UserRole;
    professional?: ProfessionalProfile;
} {
    return {
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        professional: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.professional))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    category: _ServiceCategory;
}): {
    displayName: string;
    category: ServiceCategory;
} {
    return {
        displayName: value.displayName,
        category: from_candid_ServiceCategory_n19(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    maxPrice: bigint;
    category: _ServiceCategory;
    minPrice: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    maxPrice: bigint;
    category: ServiceCategory;
    minPrice: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        maxPrice: value.maxPrice,
        category: from_candid_ServiceCategory_n19(_uploadFile, _downloadFile, value.category),
        minPrice: value.minPrice
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    customer: Principal;
    date: string;
    createdAt: bigint;
    assignedProfessional: [] | [Principal];
    address: string;
    serviceId: bigint;
    timeSlot: string;
}): {
    id: bigint;
    status: BookingStatus;
    customer: Principal;
    date: string;
    createdAt: bigint;
    assignedProfessional?: Principal;
    address: string;
    serviceId: bigint;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n8(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        date: value.date,
        createdAt: value.createdAt,
        assignedProfessional: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.assignedProfessional)),
        address: value.address,
        serviceId: value.serviceId,
        timeSlot: value.timeSlot
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dataRecovery: null;
} | {
    desktopRepair: null;
} | {
    networkSetup: null;
} | {
    laptopRepair: null;
} | {
    accessoriesSales: null;
} | {
    computerSales: null;
}): ServiceCategory {
    return "dataRecovery" in value ? ServiceCategory.dataRecovery : "desktopRepair" in value ? ServiceCategory.desktopRepair : "networkSetup" in value ? ServiceCategory.networkSetup : "laptopRepair" in value ? ServiceCategory.laptopRepair : "accessoriesSales" in value ? ServiceCategory.accessoriesSales : "computerSales" in value ? ServiceCategory.computerSales : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_ProfessionalProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionalProfile): _ProfessionalProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory | null): [] | [_ServiceCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ServiceCategory_n1(_uploadFile, _downloadFile, value));
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: UserRole;
    professional?: ProfessionalProfile;
}): {
    role: _UserRole;
    professional: [] | [_ProfessionalProfile];
} {
    return {
        role: to_candid_UserRole_n3(_uploadFile, _downloadFile, value.role),
        professional: value.professional ? candid_some(to_candid_ProfessionalProfile_n27(_uploadFile, _downloadFile, value.professional)) : candid_none()
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    category: ServiceCategory;
}): {
    displayName: string;
    category: _ServiceCategory;
} {
    return {
        displayName: value.displayName,
        category: to_candid_ServiceCategory_n1(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    dataRecovery: null;
} | {
    desktopRepair: null;
} | {
    networkSetup: null;
} | {
    laptopRepair: null;
} | {
    accessoriesSales: null;
} | {
    computerSales: null;
} {
    return value == ServiceCategory.dataRecovery ? {
        dataRecovery: null
    } : value == ServiceCategory.desktopRepair ? {
        desktopRepair: null
    } : value == ServiceCategory.networkSetup ? {
        networkSetup: null
    } : value == ServiceCategory.laptopRepair ? {
        laptopRepair: null
    } : value == ServiceCategory.accessoriesSales ? {
        accessoriesSales: null
    } : value == ServiceCategory.computerSales ? {
        computerSales: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
